# Generated by Django 3.2.3 on 2021-07-25 19:57

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/users', verbose_name='image'),
        ),
    ]
